### ISSUE TITLE
some packages in requirements.txt can be  found

### ISSUE THREAD

**Issue by LittWhite-WANG** [hijkzzz/noisy-mappo#1]
some packages in requirements.txt can be  found such as :
mkl-fft==1.1.0
mkl-random==1.1.1
protobuf==3.12.3

They don't seem to exist
![image](https://user-images.githubusercontent.com/62829998/144712374-74cb3988-df32-4301-b6f5-847bb54ce09f.png)
![Uploading image.png…]()

**Comment by hijkzzz** [comment]
Hello, I have updated requirements.txt.
